export const TOGGLE_LANDING_PAGE = 'TOGGLE_LANDING_PAGE';

export const START_LOGIN = 'START_LOGIN';

export const START_REGISTRATION = 'START_REGISTRATION';

export const CLOSE_MODAL = 'CLOSE_MODAL';
