export const TOGGLE_LANDING_PAGE = 'TOGGLE_LANDING_PAGE';

export const OPEN_MODAL_TO_LOGIN = 'OPEN_MODAL_TO_LOGIN ';
export const OPEN_MODAL_TO_REGISTRATION = 'OPEN_MODAL_TO_REGISTRATION';
export const SWITCH_TO_MODAL_TO_LOGIN = 'SWITCH_TO_LOGIN';
export const SWITCH_TO_MODAL_TO_SUCCESS = 'SWITCH_TO_MODAL_TO_SUCCESS';
export const CLOSE_MODAL = 'CLOSE_MODAL';
// login action types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const TOGGLE_PROFILE_DROPDOWN = 'TOGGLE_PROFILE_DROPDOWN';

// modal action types
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// password reset action types
export const PASSWORD_RESET_START = 'PASSWORD_RESET_START';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const USER_REGISTRATION_START = 'REGISTRATION_START';
export const USER_REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'REGISTRATION_FAIL';

// Paginate articles
export const START_FETCH_ARTICLES_FIRST_PAGE = 'START_FETCH_ARTICLES_FIRST_PAGE';
export const LOAD_MORE_ARTICLES = 'LOAD_MORE_ARTICLES';
export const END_LOADING_ARTICLES = 'END_LOADING_ARTICLES';

// Article Text Comment Box
export const SHOW_ARTICLE_TEXT_COMMENT_BOX = 'SHOW_ARTICLE_TEXT_COMMENT_BOX';
export const HIDE_ARTICLE_TEXT_COMMENT_BOX = 'HIDE_ARTICLE_TEXT_COMMENT_BOX';

export const START_FETCHING_ARTICLE_TEXT_COMMENTS = 'START_FETCHING_ARTICLE_TEXT_COMMENTS';
export const FETCHING_ARTICLE_TEXT_COMMENTS_SUCCESS = 'FETCHING_ARTICLE_TEXT_COMMENTS_SUCCESS';
export const FETCHING_ARTICLE_TEXT_COMMENTS_FAIL = 'FETCHING_ARTICLE_TEXT_COMMENTS_FAIL';

export const START_POSTING_ARTICLE_TEXT_COMMENT = 'START_POSTING_ARTICLE_TEXT_COMMENT';
export const POSTING_ARTICLE_TEXT_COMMENT_SUCCESS = 'POSTING_ARTICLE_TEXT_COMMENT_SUCCESS';
export const POSTING_ARTICLE_TEXT_COMMENT_FAIL = 'POSTING_ARTICLE_TEXT_COMMENT_FAIL';
// Notifications
export const ALL_NOTIFICATIONS = 'ALL_NOTIFICATIONS';
export const FETCH_MORE = 'FETCH_MORE';
export const READ = 'READ';
export const TOGGLE_MUTE_NOTIFICATIONS = 'TOGGLE_MUTE_NOTIFICATIONS';
